"""movement classes, events, object tracks

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-23 18:13:55.345967
"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# The spec's movement classes (Phase 4), as shipped. Frozen here: later edits happen through the app.
BUILTIN_CLASSES = [
    ("hand_enter", "Hand enters frame", "A hand comes into view.", False),
    ("hand_exit", "Hand exits frame", "A hand leaves the view.", False),
    ("reach", "Reach", "The hand moves toward an object it then touches.", True),
    ("grasp", "Grasp", "The hand closes on an object.", True),
    ("release", "Release", "The hand lets go of an object it was grasping.", True),
    ("pinch", "Pinch", "Thumb and index fingertips held together.", False),
    ("point", "Point", "Index finger extended with the other fingers curled.", False),
    ("tap", "Tap", "A fingertip touches an object briefly.", True),
    ("swipe", "Swipe", "A fast, straight sweep of the hand across the view.", False),
    ("rotate", "Rotate", "The hand turns about the camera axis.", False),
    ("push", "Push", "The hand moves away from the camera while touching an object.", True),
    ("pull", "Pull", "The hand moves toward the camera while touching an object.", True),
    ("pick_up", "Pick up", "An object is lifted with the hand grasping it.", True),
    ("put_down", "Put down", "A grasped object is lowered.", True),
    ("hold", "Hold", "An object is grasped and held still.", True),
    ("move", "Move", "A grasped object is carried sideways.", True),
    ("manipulate", "Manipulate", "Fingers work on an object while the hand stays in place.", True),
    ("press", "Press", "A fingertip rests on an object without grasping it.", True),
    ("drag", "Drag", "A fingertip slides an object along without grasping it.", True),
    (
        "gesture",
        "Gesture",
        "A static hand sign away from objects (e.g. victory, thumbs up, open palm).",
        False,
    ),
]

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movement_classes",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("builtin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("requires_object", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_movement_classes_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movement_classes")),
        sa.UniqueConstraint("name", name=op.f("uq_movement_classes_name")),
    )
    op.create_table(
        "object_tracks",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("first_frame", sa.Integer(), nullable=False),
        sa.Column("last_frame", sa.Integer(), nullable=False),
        sa.Column("frames_detected", sa.Integer(), nullable=False),
        sa.Column("missing_detections", sa.Integer(), server_default="0", nullable=False),
        sa.Column("mean_score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("mean_bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("path_length_px", sa.Float(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("last_frame >= first_frame", name=op.f("ck_object_tracks_frame_range")),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_object_tracks_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["cv_runs.id"], name=op.f("fk_object_tracks_run_id_cv_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_tracks")),
        sa.UniqueConstraint("run_id", "track_id", name=op.f("uq_object_tracks_run_id_track_id")),
    )
    op.create_index(op.f("ix_object_tracks_run_id"), "object_tracks", ["run_id"], unique=False)
    op.create_table(
        "movement_events",
        sa.Column("annotation_id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("hand_run_id", sa.UUID(), nullable=False),
        sa.Column("object_run_id", sa.UUID(), nullable=True),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("end_frame", sa.Integer(), nullable=False),
        sa.Column("start_s", sa.Float(), nullable=False),
        sa.Column("end_s", sa.Float(), nullable=False),
        sa.Column("handedness", sa.String(length=8), nullable=False),
        sa.Column("hand_track_id", sa.Integer(), nullable=False),
        sa.Column("fingers", postgresql.ARRAY(sa.String(length=8)), server_default="{}", nullable=False),
        sa.Column("object_track_id", sa.Integer(), nullable=True),
        sa.Column("object_label", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "auto_detected",
                "needs_review",
                "confirmed",
                "rejected",
                "corrected",
                name="movement_event_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="auto_detected",
            nullable=False,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_movement_events_confidence_range")
        ),
        sa.CheckConstraint("end_frame >= start_frame", name=op.f("ck_movement_events_frame_range")),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_movement_events_annotation_id_annotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["movement_classes.id"],
            name=op.f("fk_movement_events_class_id_movement_classes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hand_run_id"],
            ["cv_runs.id"],
            name=op.f("fk_movement_events_hand_run_id_cv_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_movement_events_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["object_run_id"],
            ["cv_runs.id"],
            name=op.f("fk_movement_events_object_run_id_cv_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_movement_events_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["cv_runs.id"], name=op.f("fk_movement_events_run_id_cv_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_movement_events_session_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_movement_events_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movement_events")),
        sa.UniqueConstraint("annotation_id", name=op.f("uq_movement_events_annotation_id")),
    )
    op.create_index(op.f("ix_movement_events_class_id"), "movement_events", ["class_id"], unique=False)
    op.create_index(
        op.f("ix_movement_events_model_version_id"), "movement_events", ["model_version_id"], unique=False
    )
    op.create_index(op.f("ix_movement_events_run_id"), "movement_events", ["run_id"], unique=False)
    op.create_index(op.f("ix_movement_events_session_id"), "movement_events", ["session_id"], unique=False)
    op.create_index(op.f("ix_movement_events_status"), "movement_events", ["status"], unique=False)
    op.create_index(
        "ix_movement_events_video_id_start_frame",
        "movement_events",
        ["video_id", "start_frame"],
        unique=False,
    )
    op.add_column(
        "cv_runs",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###
    # New run status: waiting on input runs (enums are VARCHAR + CHECK, see models.base.str_enum).
    op.drop_constraint(op.f("ck_cv_runs_cv_run_status"), "cv_runs", type_="check")
    op.create_check_constraint(
        "cv_run_status", "cv_runs", "status IN ('waiting', 'queued', 'running', 'succeeded', 'failed')"
    )
    classes = sa.table(
        "movement_classes",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("label", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("builtin", sa.Boolean()),
        sa.column("requires_object", sa.Boolean()),
    )
    op.bulk_insert(
        classes,
        [
            {
                "id": uuid.uuid4(),
                "name": n,
                "label": label,
                "description": d,
                "builtin": True,
                "requires_object": o,
            }
            for n, label, d, o in BUILTIN_CLASSES
        ],
    )


def downgrade() -> None:
    op.execute(
        "UPDATE cv_runs SET status = 'failed', error = 'waiting run dropped by downgrade' WHERE status = 'waiting'"
    )
    op.drop_constraint(op.f("ck_cv_runs_cv_run_status"), "cv_runs", type_="check")
    op.create_check_constraint(
        "cv_run_status", "cv_runs", "status IN ('queued', 'running', 'succeeded', 'failed')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cv_runs", "inputs")
    op.drop_index("ix_movement_events_video_id_start_frame", table_name="movement_events")
    op.drop_index(op.f("ix_movement_events_status"), table_name="movement_events")
    op.drop_index(op.f("ix_movement_events_session_id"), table_name="movement_events")
    op.drop_index(op.f("ix_movement_events_run_id"), table_name="movement_events")
    op.drop_index(op.f("ix_movement_events_model_version_id"), table_name="movement_events")
    op.drop_index(op.f("ix_movement_events_class_id"), table_name="movement_events")
    op.drop_table("movement_events")
    op.drop_index(op.f("ix_object_tracks_run_id"), table_name="object_tracks")
    op.drop_table("object_tracks")
    op.drop_table("movement_classes")
    # ### end Alembic commands ###
