"""pipelines, runs, steps, schedules, quality checks, annotated videos

Phase 7: pipeline definitions with immutable versions (a trigger refuses changes), runs with a row per step
and video, one attempt (and job) per try, cron schedules, per-video quality checks, frame hashes for
near-duplicate search, annotated-video renders, and a job heartbeat so jobs whose worker died can be
recovered. Job logs get a trigram index so a run's logs can be searched by any word or fragment.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 22:45:52.764765
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipelines",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_template", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("layout", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_pipelines_created_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipelines")),
        sa.UniqueConstraint("name", name=op.f("uq_pipelines_name")),
    )
    op.create_table(
        "pipeline_schedules",
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cron", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("only_new", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_outcome", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_pipeline_schedules_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_pipeline_schedules_pipeline_id_pipelines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_schedules")),
    )
    op.create_index(
        op.f("ix_pipeline_schedules_next_run_at"), "pipeline_schedules", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_schedules_pipeline_id"), "pipeline_schedules", ["pipeline_id"], unique=False
    )
    op.create_table(
        "pipeline_versions",
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("graph", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("graph_hash", sa.String(length=64), nullable=False),
        sa.Column("parent_version_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_pipeline_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["pipeline_versions.id"],
            name=op.f("fk_pipeline_versions_parent_version_id_pipeline_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_pipeline_versions_pipeline_id_pipelines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_versions")),
        sa.UniqueConstraint("pipeline_id", "number", name=op.f("uq_pipeline_versions_pipeline_id_number")),
    )
    op.create_index(
        op.f("ix_pipeline_versions_pipeline_id"), "pipeline_versions", ["pipeline_id"], unique=False
    )
    op.create_table(
        "annotated_videos",
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "building",
                "ready",
                "failed",
                name="annotated_video_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("codec", sa.String(length=16), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("frames", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_annotated_videos_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_annotated_videos_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_annotated_videos_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotated_videos")),
    )
    op.create_index(op.f("ix_annotated_videos_video_id"), "annotated_videos", ["video_id"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="pipeline_run_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum(
                "manual",
                "schedule",
                name="pipeline_run_trigger",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("schedule_id", sa.UUID(), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("video_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_pipeline_runs_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_pipeline_runs_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_pipeline_runs_pipeline_id_pipelines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["pipeline_schedules.id"],
            name=op.f("fk_pipeline_runs_schedule_id_pipeline_schedules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["pipeline_versions.id"],
            name=op.f("fk_pipeline_runs_version_id_pipeline_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_runs")),
        sa.UniqueConstraint("pipeline_id", "number", name=op.f("uq_pipeline_runs_pipeline_id_number")),
    )
    op.create_index(op.f("ix_pipeline_runs_pipeline_id"), "pipeline_runs", ["pipeline_id"], unique=False)
    op.create_index(op.f("ix_pipeline_runs_schedule_id"), "pipeline_runs", ["schedule_id"], unique=False)
    op.create_index(
        "ix_pipeline_runs_status_created_at", "pipeline_runs", ["status", "created_at"], unique=False
    )
    op.create_table(
        "video_frame_hashes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("frame", sa.Integer(), nullable=False),
        sa.Column("hash", sa.BigInteger(), nullable=False),
        sa.Column("b0", sa.Integer(), nullable=False),
        sa.Column("b1", sa.Integer(), nullable=False),
        sa.Column("b2", sa.Integer(), nullable=False),
        sa.Column("b3", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_video_frame_hashes_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_frame_hashes")),
    )
    op.create_index("ix_video_frame_hashes_b0", "video_frame_hashes", ["b0"], unique=False)
    op.create_index("ix_video_frame_hashes_b1", "video_frame_hashes", ["b1"], unique=False)
    op.create_index("ix_video_frame_hashes_b2", "video_frame_hashes", ["b2"], unique=False)
    op.create_index("ix_video_frame_hashes_b3", "video_frame_hashes", ["b3"], unique=False)
    op.create_index(op.f("ix_video_frame_hashes_video_id"), "video_frame_hashes", ["video_id"], unique=False)
    op.create_table(
        "video_quality_checks",
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("check", sa.String(length=32), nullable=False),
        sa.Column("flag", sa.String(length=32), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_video_quality_checks_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_video_quality_checks_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_quality_checks")),
    )
    op.create_index(
        "ix_video_quality_checks_video_id_check_created_at",
        "video_quality_checks",
        ["video_id", "check", "created_at"],
        unique=False,
    )
    op.create_table(
        "pipeline_step_runs",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("step_type", sa.String(length=64), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "queued",
                "running",
                "retry_wait",
                "succeeded",
                "failed",
                "skipped",
                "cancelled",
                name="pipeline_step_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_pipeline_step_runs_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_pipeline_step_runs_run_id_pipeline_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_pipeline_step_runs_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_step_runs")),
        sa.UniqueConstraint(
            "run_id",
            "node_id",
            "video_id",
            name=op.f("uq_pipeline_step_runs_run_id_node_id_video_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_pipeline_step_runs_run_id"), "pipeline_step_runs", ["run_id"], unique=False)
    op.create_index(
        "ix_pipeline_step_runs_run_id_node_id_status",
        "pipeline_step_runs",
        ["run_id", "node_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_pipeline_step_runs_status_retry_at", "pipeline_step_runs", ["status", "retry_at"], unique=False
    )
    op.create_index(op.f("ix_pipeline_step_runs_video_id"), "pipeline_step_runs", ["video_id"], unique=False)
    op.create_table(
        "pipeline_step_attempts",
        sa.Column("step_run_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "queued",
                "running",
                "retry_wait",
                "succeeded",
                "failed",
                "skipped",
                "cancelled",
                name="pipeline_attempt_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_pipeline_step_attempts_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_pipeline_step_attempts_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["step_run_id"],
            ["pipeline_step_runs.id"],
            name=op.f("fk_pipeline_step_attempts_step_run_id_pipeline_step_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_step_attempts")),
        sa.UniqueConstraint(
            "step_run_id", "number", name=op.f("uq_pipeline_step_attempts_step_run_id_number")
        ),
    )
    op.create_index(
        op.f("ix_pipeline_step_attempts_job_id"), "pipeline_step_attempts", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_step_attempts_step_run_id"), "pipeline_step_attempts", ["step_run_id"], unique=False
    )
    op.add_column("jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER pipeline_versions_immutable BEFORE UPDATE OR DELETE ON pipeline_versions "
        "FOR EACH ROW EXECUTE FUNCTION egolabs_refuse_change()"
    )
    # Search a run's logs by any fragment of the message or its structured data (pg_trgm is a trusted
    # extension: the database owner can create it).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX ix_job_logs_search_trgm ON job_logs "
        "USING gin ((message || ' ' || data::text) gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_job_logs_search_trgm")
    op.execute("DROP TRIGGER IF EXISTS pipeline_versions_immutable ON pipeline_versions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "heartbeat_at")
    op.drop_index(op.f("ix_pipeline_step_attempts_step_run_id"), table_name="pipeline_step_attempts")
    op.drop_index(op.f("ix_pipeline_step_attempts_job_id"), table_name="pipeline_step_attempts")
    op.drop_table("pipeline_step_attempts")
    op.drop_index(op.f("ix_pipeline_step_runs_video_id"), table_name="pipeline_step_runs")
    op.drop_index("ix_pipeline_step_runs_status_retry_at", table_name="pipeline_step_runs")
    op.drop_index("ix_pipeline_step_runs_run_id_node_id_status", table_name="pipeline_step_runs")
    op.drop_index(op.f("ix_pipeline_step_runs_run_id"), table_name="pipeline_step_runs")
    op.drop_table("pipeline_step_runs")
    op.drop_index("ix_video_quality_checks_video_id_check_created_at", table_name="video_quality_checks")
    op.drop_table("video_quality_checks")
    op.drop_index(op.f("ix_video_frame_hashes_video_id"), table_name="video_frame_hashes")
    op.drop_index("ix_video_frame_hashes_b3", table_name="video_frame_hashes")
    op.drop_index("ix_video_frame_hashes_b2", table_name="video_frame_hashes")
    op.drop_index("ix_video_frame_hashes_b1", table_name="video_frame_hashes")
    op.drop_index("ix_video_frame_hashes_b0", table_name="video_frame_hashes")
    op.drop_table("video_frame_hashes")
    op.drop_index("ix_pipeline_runs_status_created_at", table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_schedule_id"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_pipeline_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index(op.f("ix_annotated_videos_video_id"), table_name="annotated_videos")
    op.drop_table("annotated_videos")
    op.drop_index(op.f("ix_pipeline_versions_pipeline_id"), table_name="pipeline_versions")
    op.drop_table("pipeline_versions")
    op.drop_index(op.f("ix_pipeline_schedules_pipeline_id"), table_name="pipeline_schedules")
    op.drop_index(op.f("ix_pipeline_schedules_next_run_at"), table_name="pipeline_schedules")
    op.drop_table("pipeline_schedules")
    op.drop_table("pipelines")
    # ### end Alembic commands ###
