"""review, event versions, auto-accept rules

Phase 5: movement events become versioned (a correction is a new event whose parent is the prediction), every
status change is logged (`movement_event_reviews`), auto-accept rules and bulk review batches are recorded,
and events carry model disagreement for the active-learning queue. Events reviewed before this migration were
reviewed one at a time by a person (Phase 4 had no bulk or rule-based review), so they get method `individual`.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 21:08:14.466897
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_batches",
        sa.Column(
            "action",
            sa.Enum(
                "auto_detected",
                "needs_review",
                "confirmed",
                "rejected",
                "corrected",
                name="review_batch_action",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undone_by", sa.UUID(), nullable=True),
        sa.Column("undone_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_review_batches_actor_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["undone_by"], ["users.id"], name=op.f("fk_review_batches_undone_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_batches")),
    )
    op.create_table(
        "review_rules",
        sa.Column("class_id", sa.UUID(), nullable=True),
        sa.Column("min_confidence", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "min_confidence >= 0 AND min_confidence <= 1", name=op.f("ck_review_rules_min_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["movement_classes.id"],
            name=op.f("fk_review_rules_class_id_movement_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_review_rules_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_review_rules_updated_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_rules")),
    )
    op.create_index(
        "uq_review_rules_class_id",
        "review_rules",
        ["class_id"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "movement_event_reviews",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "auto_detected",
                "needs_review",
                "confirmed",
                "rejected",
                "corrected",
                name="review_from_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "auto_detected",
                "needs_review",
                "confirmed",
                "rejected",
                "corrected",
                name="review_to_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum(
                "individual",
                "bulk",
                "auto_rule",
                "correction",
                "inspector",
                "undo",
                name="review_log_method",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("related_event_id", sa.UUID(), nullable=True),
        sa.Column("class_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_movement_event_reviews_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["review_batches.id"],
            name=op.f("fk_movement_event_reviews_batch_id_review_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["movement_classes.id"],
            name=op.f("fk_movement_event_reviews_class_id_movement_classes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["movement_events.id"],
            name=op.f("fk_movement_event_reviews_event_id_movement_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["related_event_id"],
            ["movement_events.id"],
            name=op.f("fk_movement_event_reviews_related_event_id_movement_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["review_rules.id"],
            name=op.f("fk_movement_event_reviews_rule_id_review_rules"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movement_event_reviews")),
    )
    op.create_index(
        "ix_movement_event_reviews_actor_id_created_at",
        "movement_event_reviews",
        ["actor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movement_event_reviews_batch_id"), "movement_event_reviews", ["batch_id"], unique=False
    )
    op.create_index(
        "ix_movement_event_reviews_event_id_created_at",
        "movement_event_reviews",
        ["event_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "movement_events",
        sa.Column(
            "review_method",
            sa.Enum(
                "individual",
                "bulk",
                "auto_rule",
                "correction",
                "inspector",
                "undo",
                name="review_method",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
    )
    op.add_column("movement_events", sa.Column("review_batch_id", sa.UUID(), nullable=True))
    op.add_column("movement_events", sa.Column("review_rule_id", sa.UUID(), nullable=True))
    op.add_column(
        "movement_events",
        sa.Column(
            "source",
            sa.Enum(
                "auto",
                "human",
                "auto_corrected",
                name="movement_event_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="auto",
            nullable=False,
        ),
    )
    op.add_column("movement_events", sa.Column("parent_event_id", sa.UUID(), nullable=True))
    op.add_column("movement_events", sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("movement_events", sa.Column("disagreement", sa.Float(), nullable=True))
    op.add_column(
        "movement_events", sa.Column("compared_versions", sa.Integer(), server_default="0", nullable=False)
    )
    op.alter_column(
        "movement_events", "confidence", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.create_index(
        "ix_movement_events_class_id_status", "movement_events", ["class_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_movement_events_parent_event_id"), "movement_events", ["parent_event_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_movement_events_review_batch_id_review_batches"),
        "movement_events",
        "review_batches",
        ["review_batch_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_movement_events_parent_event_id_movement_events"),
        "movement_events",
        "movement_events",
        ["parent_event_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_movement_events_review_rule_id_review_rules"),
        "movement_events",
        "review_rules",
        ["review_rule_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        op.f("ck_movement_events_auto_has_confidence"),
        "movement_events",
        "source <> 'auto' OR confidence IS NOT NULL",
    )
    op.create_check_constraint(
        op.f("ck_movement_events_correction_has_parent"),
        "movement_events",
        "source = 'auto' OR parent_event_id IS NOT NULL",
    )
    op.create_check_constraint(
        op.f("ck_movement_events_disagreement_range"),
        "movement_events",
        "disagreement IS NULL OR (disagreement >= 0 AND disagreement <= 1)",
    )
    op.execute("UPDATE movement_events SET review_method = 'individual' WHERE reviewed_by IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for name in ("disagreement_range", "correction_has_parent", "auto_has_confidence"):
        op.drop_constraint(op.f(f"ck_movement_events_{name}"), "movement_events", type_="check")
    # Corrections have no confidence of their own; they can't exist without these columns.
    op.execute("DELETE FROM movement_events WHERE source <> 'auto'")
    op.drop_constraint(
        op.f("fk_movement_events_review_rule_id_review_rules"), "movement_events", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_movement_events_parent_event_id_movement_events"), "movement_events", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_movement_events_review_batch_id_review_batches"), "movement_events", type_="foreignkey"
    )
    op.drop_index(op.f("ix_movement_events_parent_event_id"), table_name="movement_events")
    op.drop_index("ix_movement_events_class_id_status", table_name="movement_events")
    op.alter_column(
        "movement_events", "confidence", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.drop_column("movement_events", "compared_versions")
    op.drop_column("movement_events", "disagreement")
    op.drop_column("movement_events", "superseded_at")
    op.drop_column("movement_events", "parent_event_id")
    op.drop_column("movement_events", "source")
    op.drop_column("movement_events", "review_rule_id")
    op.drop_column("movement_events", "review_batch_id")
    op.drop_column("movement_events", "review_method")
    op.drop_index("ix_movement_event_reviews_event_id_created_at", table_name="movement_event_reviews")
    op.drop_index(op.f("ix_movement_event_reviews_batch_id"), table_name="movement_event_reviews")
    op.drop_index("ix_movement_event_reviews_actor_id_created_at", table_name="movement_event_reviews")
    op.drop_table("movement_event_reviews")
    op.drop_index("uq_review_rules_class_id", table_name="review_rules", postgresql_nulls_not_distinct=True)
    op.drop_table("review_rules")
    op.drop_table("review_batches")
    # ### end Alembic commands ###
