"""Core schema (spec Phase 0). Import everything here so Alembic sees the full metadata."""

from egolabs.models.activity import Event, LineageEdge
from egolabs.models.base import Base
from egolabs.models.catalog import CaptureSession, Dataset, Device, Frame, Operator, Video, dataset_sessions
from egolabs.models.cv import CvRun, HandTrack, ObjectTrack
from egolabs.models.datasets import DatasetExport, DatasetVersion, DatasetVersionCheck, DatasetVersionSample
from egolabs.models.enums import (
    ACTIVE_JOB_STATUSES,
    AnnotationCategory,
    AnnotationSource,
    AnnotationType,
    AssignmentStatus,
    BuildStatus,
    CvRunKind,
    CvRunStatus,
    ExportFormat,
    JobStatus,
    LogLevel,
    MovementEventStatus,
    PipelineRunStatus,
    ProcessingHold,
    ReviewMethod,
    RevisionAction,
    Role,
    RunTrigger,
    SplitGroup,
    StepStatus,
    UploadKind,
    UploadStatus,
    VideoSource,
    VideoStatus,
)
from egolabs.models.ingest import MetadataFile, Upload
from egolabs.models.jobs import Job, JobLog
from egolabs.models.ml import Annotation, AnnotationRevision, ModelVersion
from egolabs.models.movement import MovementClass, MovementEvent, MovementEventReview, ReviewBatch, ReviewRule
from egolabs.models.pipelines import (
    AnnotatedVideo,
    Pipeline,
    PipelineRun,
    PipelineSchedule,
    PipelineStepAttempt,
    PipelineStepRun,
    PipelineVersion,
    VideoFrameHash,
    VideoQualityCheck,
)
from egolabs.models.users import AppSetting, SignIn, User
from egolabs.models.work import AnnotationAssignment

__all__ = [
    "AppSetting",
    "ProcessingHold",
    "SignIn",
    "VideoQualityCheck",
    "VideoFrameHash",
    "StepStatus",
    "RunTrigger",
    "PipelineVersion",
    "PipelineStepRun",
    "PipelineStepAttempt",
    "PipelineSchedule",
    "PipelineRunStatus",
    "PipelineRun",
    "Pipeline",
    "AnnotatedVideo",
    "ACTIVE_JOB_STATUSES",
    "Annotation",
    "AnnotationAssignment",
    "AnnotationCategory",
    "AnnotationRevision",
    "AnnotationSource",
    "AnnotationType",
    "AssignmentStatus",
    "Base",
    "BuildStatus",
    "CaptureSession",
    "CvRun",
    "CvRunKind",
    "CvRunStatus",
    "Dataset",
    "DatasetExport",
    "DatasetVersion",
    "DatasetVersionCheck",
    "DatasetVersionSample",
    "Device",
    "Event",
    "ExportFormat",
    "Frame",
    "HandTrack",
    "Job",
    "JobLog",
    "JobStatus",
    "LineageEdge",
    "LogLevel",
    "MetadataFile",
    "ModelVersion",
    "MovementClass",
    "MovementEvent",
    "MovementEventReview",
    "MovementEventStatus",
    "ObjectTrack",
    "Operator",
    "ReviewBatch",
    "ReviewMethod",
    "ReviewRule",
    "RevisionAction",
    "Role",
    "SplitGroup",
    "Upload",
    "UploadKind",
    "UploadStatus",
    "User",
    "Video",
    "VideoSource",
    "VideoStatus",
    "dataset_sessions",
]
